/* Autogenerated by bin2c */
// 图标、着色器二进制文件
#pragma once
#include <stdint.h>	// c99中引进的一个标准C库的头文件
// extern：表示变量或者函数的定义在别的文件中，提示编译器遇到此变量和函数时在其他模块中寻找其定义。extern 也可用来进行链接指定。
extern uint8_t comb_png[];
extern uint32_t comb_png_size;

extern uint8_t delete_stroke_png[];
extern uint32_t delete_stroke_png_size;

extern uint8_t loadmesh_png[];
extern uint32_t loadmesh_png_size;

extern uint8_t scare_png[];
extern uint32_t scare_png_size;

extern uint8_t sing_dir_png[];
extern uint32_t sing_dir_png_size;

extern uint8_t sing_pos_png[];
extern uint32_t sing_pos_png_size;

extern uint8_t instantmeshes_png[];
extern uint32_t instantmeshes_png_size;

extern uint8_t shader_flowline_frag[];
extern uint32_t shader_flowline_frag_size;

extern uint8_t shader_lines_frag[];
extern uint32_t shader_lines_frag_size;

extern uint8_t shader_mesh_frag[];
extern uint32_t shader_mesh_frag_size;

extern uint8_t shader_orientation_field_frag[];
extern uint32_t shader_orientation_field_frag_size;

extern uint8_t shader_position_field_frag[];
extern uint32_t shader_position_field_frag_size;

extern uint8_t shader_quadmesh_frag[];
extern uint32_t shader_quadmesh_frag_size;

extern uint8_t shader_singularity_frag[];
extern uint32_t shader_singularity_frag_size;

extern uint8_t shader_flowline_vert[];
extern uint32_t shader_flowline_vert_size;

extern uint8_t shader_lines_vert[];
extern uint32_t shader_lines_vert_size;

extern uint8_t shader_mesh_vert[];
extern uint32_t shader_mesh_vert_size;

extern uint8_t shader_orientation_field_vert[];
extern uint32_t shader_orientation_field_vert_size;

extern uint8_t shader_point_vert[];
extern uint32_t shader_point_vert_size;

extern uint8_t shader_position_field_vert[];
extern uint32_t shader_position_field_vert_size;

extern uint8_t shader_quadmesh_vert[];
extern uint32_t shader_quadmesh_vert_size;

extern uint8_t shader_singularity_vert[];
extern uint32_t shader_singularity_vert_size;

extern uint8_t shader_mesh_geo[];
extern uint32_t shader_mesh_geo_size;

extern uint8_t shader_orientation_field_geo[];
extern uint32_t shader_orientation_field_geo_size;

extern uint8_t shader_point_geo[];
extern uint32_t shader_point_geo_size;

extern uint8_t shader_singularity_geo[];
extern uint32_t shader_singularity_geo_size;